name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Запуск раз в день (в 00:00 UTC)
  workflow_dispatch:  # Позволяет запустить вручную

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/VariantConst/OpenWebUI-Monitor.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge --allow-unrelated-histories upstream/main -m "Merge latest changes from upstream"
      
      - name: Push changes to fork
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
